### PR TITLE
reqs - cc sender in authorisation request emails

### PR DESCRIPTION
**Pull request by iaincrawf**
+ don't change req number - was effectively deleting them if you updated anything

### CODE REVIEW

**Review by richardiphillips — APPROVED** [review]

**Comment by richardiphillips** [comment]
I noticed you had hardcoded urls in the domain service e.g. https://app.linn.co.uk/purchasing..

Would be much better to pass the root in as a variable or look it up. I'd prefer to get ioc to look up APP_ROOT and pass it in

**Comment by iaincrawf** [comment]
> I noticed you had hardcoded urls in the domain service e.g. https://app.linn.co.uk/purchasing..
> 
> Would be much better to pass the root in as a variable or look it up. I'd prefer to get ioc to look up APP_ROOT and pass it in

I remember thinking I should change that at the time and forgot, is using ConfigurationManager["APP_ROOT"] what you mean with IOC or something else? It seems to work ok

**Comment by richardiphillips** [comment]
> 

having the configuration manager fishing things out isn't really nice domain code. Much better to make it a constructor variable and pass it in from the IOC. There should be examples in the Messaging Extensions.

**Comment by richardiphillips** [comment]
> > 
> 
> having the configuration manager fishing things out isn't really nice domain code. Much better to make it a constructor variable and pass it in from the IOC. There should be examples in the Messaging Extensions.

Actually see how Lewis did the PdfService in ServiceExtensions. That means you can then test that the right uris are being generated too

**Pull request merged**
